### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by k8hertweck**
As drafted by @dwinter. Fairly straightforward, but we should probably include a mention of where to report violations (all members of organizing committee? I'm personally OK with this, but what do you think?).

### CODE REVIEW

**Comment by fmichonneau** [comment]
Yes, any member of the organizing committee seems like a good option. Should we create an email alias or just include our phone numbers/email addresses?

**Comment by k8hertweck** [comment]
I'm ok with offering my name as one of the points of contact for reporting regarding the Code of Conduct. It would be great if a few other people would agree to this as well. Anyone? @fmichonneau @dwinter @daisieh

**Comment by daisieh** [comment]
I agree. I'd be fine with using my name/info as a point of contact as well.

**Comment by k8hertweck** [comment]
Great, I've added Daisie and I as points of contact. This should be ready to merge.

**Pull request merged**
